# Define global variables
variables:
- group: 'terraform-backend'
- group: 'terraform-system'

# Define stages
stages:
- stage: Validate
  pool:
    vmImage: 'ubuntu-latest'
  
  # Define jobs
  jobs:
  - job: Import
    continueOnError: false
    
    # Define steps
    steps:
    
    # Install Terraform
    - task: TerraformInstaller@0
      displayName: 'Terraform Install'
      inputs:
        terraformVersion: '$(terraformVersion)'
    
    # Initialise Terraform
    - task: TerraformCLI@0
      displayName: 'Terraform Initialise'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/v25/'
        backendType: 'azurerm'
        backendServiceArm: '$(backendServiceArm)'
        ensureBackend: true
        backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
        backendAzureRmResourceGroupLocation: '$(backendAzureRmResourceGroupLocation)'
        backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
        backendAzureRmContainerName: '$(backendAzureRmContainerName)'
        backendAzureRmKey: '$(backendAzureRmKey)'
    
    # Validate Terraform
    - task: TerraformCLI@0
      displayName: 'Terraform Validate'
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/v25/'
    
    # Download Regula
    - task: DownloadGitHubRelease@0
      displayName: 'Download Regula'
      inputs:
        connection: 'wesley-trust'
        userRepository: 'fugue/regula'
        defaultVersionType: 'latest'
        itemPattern: '*Linux_x86_64.tar.gz'
        downloadPath: '$(System.ArtifactsDirectory)/regula' 
    
    # Configure Regula
    - bash: |
        # Change to directory containing regula download
        cd $(System.ArtifactsDirectory)/regula
        # Add filename to variable
        REGULA=$(ls -p | grep -v /)
        # Extract archive
        tar -xf $REGULA
        # Remove archive
        rm --f $REGULA
        # Add Regula to PATH
        echo "##vso[task.prependpath]$(System.ArtifactsDirectory)/regula"
      name: 'ConfigureRegula'
      displayName: 'Configure Regula'
    
    # Scan Terraform files with Regula
    - bash: |
        # Scan files with Regula
        regula run $(System.DefaultWorkingDirectory)/v25/ -i $(System.DefaultWorkingDirectory)/v25/rules/ -s critical
      name: 'RegulaScan'
      displayName: 'Scan Terraform files with Regula'
- stage: Plan
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Validate
  
  # Define jobs
  jobs:
  - job: Evaluate
    continueOnError: false
    
    # Define steps
    steps:
    
    # Install Terraform
    - task: TerraformInstaller@0
      displayName: 'Terraform Install'
      inputs:
        terraformVersion: '$(terraformVersion)'
    
    # Initialise Terraform
    - task: TerraformCLI@0
      displayName: 'Terraform Initialise'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/v25/'
        backendType: 'azurerm'
        backendServiceArm: '$(backendServiceArm)'
        ensureBackend: true
        backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
        backendAzureRmResourceGroupLocation: '$(backendAzureRmResourceGroupLocation)'
        backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
        backendAzureRmContainerName: '$(backendAzureRmContainerName)'
        backendAzureRmKey: '$(backendAzureRmKey)'
    
    # Create artifact directory
    - bash: |
          mkdir -p $(Pipeline.Workspace)/Output
      name: 'Directory'
      displayName: 'Create artifact directory'
    
    # Create Terraform Plan
    - task: TerraformCLI@0
      name: 'Plan'
      displayName: 'Terraform Plan'
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/v25/'
        environmentServiceName: '$(backendServiceArm)'
        publishPlanResults: 'terraform.tfplan'
        commandOptions: '-out=$(Pipeline.Workspace)/Output/terraform.tfplan -detailed-exitcode'
    
    # Download Regula
    - task: DownloadGitHubRelease@0
      displayName: 'Download Regula'
      inputs:
        connection: 'wesley-trust'
        userRepository: 'fugue/regula'
        defaultVersionType: 'latest'
        itemPattern: '*Linux_x86_64.tar.gz'
        downloadPath: '$(System.ArtifactsDirectory)/regula' 
    
    # Configure Regula
    - bash: |
        # Change to directory containing regula download
        cd $(System.ArtifactsDirectory)/regula
        # Add filename to variable
        REGULA=$(ls -p | grep -v /)
        # Extract archive
        tar -xf $REGULA
        # Remove archive
        rm --f $REGULA
        # Add Regula to PATH
        echo "##vso[task.prependpath]$(System.ArtifactsDirectory)/regula"
      name: 'ConfigureRegula'
      displayName: 'Configure Regula'
    
    # Scan Terraform Plan with Regula
    - bash: |
        # Set working directory
        cd $(System.DefaultWorkingDirectory)/v25/
        # Generate JSON plan
        terraform show -json $(Pipeline.Workspace)/Output/terraform.tfplan >$(System.ArtifactsDirectory)/plan.json
        # Scan plan
        regula run $(System.ArtifactsDirectory)/plan.json -i $(System.DefaultWorkingDirectory)/v25/rules/ -s high
      name: 'RegulaScan'
      displayName: 'Scan Terraform Plan with Regula'
    
    # Set variable
    - bash: |
        if [ "$TERRAFORM_PLAN_HAS_CHANGES" = true ] ; then
          echo "##vso[task.setvariable variable=ShouldRun;isOutput=true]true"
          fi
      name: 'Variable'
      displayName: 'Set variable'
    
    # Publish Terraform Plan artifact
    - task: PublishPipelineArtifact@1
      displayName: 'Publish plan artifact'
      inputs:
        targetPath: '$(Pipeline.Workspace)/Output'
        artifact: 'Evaluate'
        publishLocation: 'pipeline'
- stage: Apply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Plan
  condition: and(succeeded(), eq(dependencies.Plan.outputs['Evaluate.Variable.ShouldRun'], 'true'))
  
  # Define jobs
  jobs:
  - deployment: Deploy
    continueOnError: false
    environment: $(Environment)

    # Define strategy
    strategy:
     runOnce:
       deploy:
        
        # Define steps
        steps:

          # Checkout associated repo
          - checkout: self
          
          # Install Terraform
          - task: TerraformInstaller@0
            displayName: 'Terraform Install'
            inputs:
              terraformVersion: '$(terraformVersion)'
          
          # Initialise Terraform
          - task: TerraformCLI@0
            displayName: 'Terraform Initialise'
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/v25/'
              backendType: 'azurerm'
              backendServiceArm: '$(backendServiceArm)'
              ensureBackend: true
              backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
              backendAzureRmResourceGroupLocation: '$(backendAzureRmResourceGroupLocation)'
              backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
              backendAzureRmContainerName: '$(backendAzureRmContainerName)'
              backendAzureRmKey: '$(backendAzureRmKey)'
          
          # Apply Terraform Plan
          - task: TerraformCLI@0
            displayName: 'Terraform Apply'
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/v25/'
              environmentServiceName: '$(backendServiceArm)'
              commandOptions: '$(Pipeline.Workspace)/Evaluate/terraform.tfplan'